version: "3.9"
services:
  wallet:
    build: ./wallet
    ports:
      - "3000:3000"
  # TODO: have kratos use config file in ory
  kratos:
    image: "oryd/kratos"
  # TODO: have kratos use config file in oathkeeper
  oathkeeper:
    image: "oryd/oathkeeper"